### ISSUE TITLE
Option "guess" pour propriété rnb_id dans endpoint ADS

### ISSUE THREAD

**Issue by pe-beta** [fab-geocommuns/RNB-coeur#162]
## Todo

- [x] calcul de ville des ads quand un batiment 
- [x] validator : si rnb_id est "guess", la geometry doit être un polygon
- [ ] verifier qu'après le guess, l'ads ne contient maximum qu'une fois un batiment en particulier
- [x] guess => recherche puis attache du meilleur batiment ou création

## Description

En l'état actuel, le lien entre ADS et bâtiment créé au sein de notre API est soit : 
- entre un bâtiment **présent** dans le RNB et une ADS. La jonction se fait via le rnb_id au sein du endpoint
- entre un bâtiment **absent** du RNB et une ADS. Pour cela, on indique "new" comme rnb_id, dans la requête et on ajoute obligatoirement un point ou un polygon réprésentant le bâtiment.

Le branchement avec Cart@DS va nécessiter un troisième scénario, du fait de certaines contraintes :
- Cat@DS ne va pas envoyer les rnb_id
- nous ne savons pas si les bâtiments envoyés sont présents ou non dans le RNB

Il va donc s'agir de **deviner** si l'ADS concerne un bâtiment du RNB ou non. Pour cela on introduit une nouvelle possibilité de valeur pour le champs rnb_id : "guess". Le fonctionnement : 

- fonctionne en création ou modification d'ADS
- nécessite d'avoir le polygon du bâtiment dans la requête. Pas de guess sur point.
- l'algo de rapprochement est à créer (distance d'Hausdorff comme première piste. cf expérimentation avec Grenoble)
- difficulté : on aura un problème si un nouveau bâtiment va venir remplacer un ancien sur une emprise quasi identique (ex: en ville, un immeuble mitoyen sur plusieurs côtés). Peut être peut-on prendre en compte l'information qu'il s'agit d'une construction neuve dispo dans l'ADS ?
- en fonction du résultat de l'algo, on attribue l'ADS à un bâtiment présent dans le RNB ou bien, on créé un nouveau bâtiment au sein du RNB

**Comment by fchabouis** [comment]
Je pense que je peux fermer pour le moment quitte à rouvrir plus tard lorsqu'on s'occupera des ADS.
