### ISSUE TITLE
Endpoint création

### ISSUE THREAD

**Issue by pe-beta** [fab-geocommuns/RNB-coeur#47]
Requêtes POST uniquement
URL : rnb-api.beta.gouv.fr/api/alpha/ads

## Champs

- issue_number
- issue_date
- bdgs_rels[]

### Champ bdgs_rels 

- rnb_id (ou "new")
- latitude (seulement si rnb_id == new)
- longitude (seulement si rnb_id == new)
- operation (build, demolish, modify, other ?)

## todo

- [x] generate_id sur les bâtiments

## validation des données
- [x] issue_number = unique
- [x] issue_date = date
- [x] rnb_id = "new" ou existant
- [x] latitude = float
- [x] longitude = float
- [x] operations = parmi les choix dispos (build, transform, demolish, other)
- [x] si rnb_id == new, on a besoin de lat et lng
- [x] batiment une seule fois dans une ADS
